data_handler:
  class: "CustomFeatures"
  module_path: "scripts.feature_engineering.custom_modules"
  kwargs:
    start_time: "2010-01-01"
    end_time: "2025-12-31"
    fit_start_time: "2010-01-01"
    fit_end_time: "2019-12-31"

    instruments: ['US_SP500', 'JP_225', 'EU_STOXX50', 'HK_HSI']


    learn_processors:
      # dataset structure transformation, must be the first processor in the list
      - class: "CrossMarketSpilloverProcessor"
        module_path: "scripts.feature_engineering.custom_processors"
        kwargs:
          target_instrument: 'JP_225'

      # macro data broadcasting, must be after the dataset structure transformation processor
      - class: "MacroBroadcastProcessor"
        module_path: "scripts.feature_engineering.custom_processors"
        kwargs:
          macro_tickers: ['10Y_US', '10Y_JP', 'GOLD', 'BCO', 'DXY', 'USD_JPY', 'VIX']
          fields: ['$close']
          make_stationary: true

      - class: "DropnaProcessor"
        kwargs:
          fields_group: "feature"

      - class: "DropnaLabel"

      # feature normalization, must be after all feature engineering processors
      - class: "RobustZScoreNorm"
        kwargs:
            fields_group: "feature"
            clip_outlier: true

    infer_processors:
      # there mustn't be DropnaLabel processor in the infer_processors, otherwise there will be no data for inference after dropping na labels
      - class: "CrossMarketSpilloverProcessor"
        module_path: "scripts.feature_engineering.custom_processors"
        kwargs:
          target_instrument: 'JP_225'

      - class: "MacroBroadcastProcessor"
        module_path: "scripts.feature_engineering.custom_processors"
        kwargs:
          macro_tickers: [ '10Y_US', '10Y_JP', 'GOLD', 'BCO', 'DXY', 'USD_JPY', 'VIX' ]
          fields: [ '$close' ]
          make_stationary: true

      - class: "DropnaProcessor"
        kwargs:
          fields_group: "feature"

      - class: "RobustZScoreNorm"
        kwargs:
            fields_group: "feature"
            clip_outlier: true
