model:
  class: AdvancedTransformerModel
  module_path: custom_models
  kwargs:
    d_feat: 20 # 20 best
    d_model: 16
    num_layers: 2 # 1 or 2
    nhead: 2
    dropout: 0.4 # 0.4 best
    batch_size: 32 # 32 best
    n_epochs: 300
    step_len: 20

    lr: 0.00007 # 0.00005 best
    T_max: 200
    eta_min: 0.00001

    early_stop: 40
    loss: mse
    optimizer: adam
    optimizer_kwargs:
      weight_decay: 0.00001
    GPU: -1

dataset:
  class: DatasetH
  module_path: qlib.data.dataset
  kwargs:
    handler: {}
    segments:
      train: ["2010-01-01","2019-12-31" ]
      valid: ["2020-01-01","2021-12-31"]
      test: ["2022-01-01","2025-12-31"]